---
kamailio:
  lb:
    block_useragents:
      action: reject
      block_absent: no
      block_empty: no
      enable: yes
      mode: blacklist
      ua_patterns:
      - 'friendly-scanner'
  proxy:
    presence:
      enable: 'yes'
    fritzbox:
      prefixes:
        - '112'
        - '110'
        - '118[0-9]{2}'
    stir:
      enable: 'yes'
      domains:
        - name: invite-peerout-stir.scenarios.test
          private_key: /etc/kamailio/stir/invite-peerout-stir.scenarios.test.key
        - name: invite-trusted-peerout-stir.scenarios.test
          private_key: /etc/kamailio/stir/invite-peerout-stir.scenarios.test.key
        - name: invite-stir.scenarios.test
          private_key: /etc/kamailio/stir/invite-peerout-stir.scenarios.test.key
