---
b2b:
  sbc:
    xfer:
      blind_immediate_release: yes
      enable: yes
kamailio:
  proxy:
    allow_refer_method: yes
    presence:
      enable: yes
    skip_cf_loop: 'yes'
pbx:
  enable: yes
