---
b2b:
  sbc:
    xfer:
      blind_immediate_release: no
      enable: no
kamailio:
  proxy:
    allow_refer_method: no
    generate_responder_cdr_data: no
    lnp:
      enable: no
    pre_announce_keep_codec: yes
    pre_announce_keep_port: yes
    skip_cf_loop: 'yes'
